### ISSUE TITLE
yolov8剪枝比率问题

### ISSUE THREAD

**Issue by pppppsb** [JasonSloan/learning-notebook#1]
老哥你好，我走了一遍你的yolov8剪枝，我跑的是yolov8n，前面的训练、稀疏化都没问题，但是剪枝的时候显示最多只能减0.31，然后我想的是会不会因为我剪的是yolov8n，所以我又换成yolov8s，结果也是最多只能剪0.4+，请问这是什么情况？想复现你剪的0.8.谢谢老哥！ @JasonSloan

**Comment by JasonSloan** [comment]
我想会不会是你稀疏化训练的轮数不够, 或者L1正则惩罚项系数太小, 导致稀疏训练出来的模型参数没有产生稀疏化的效果

**Comment by JasonSloan** [comment]
> 我想会不会是你稀疏化训练的轮数不够, 或者L1正则惩罚项系数太小, 导致稀疏训练出来的模型参数没有产生稀疏化的效果

**Comment by gjd2017** [comment]
> > 我想会不会是你稀疏化训练的轮数不够, 或者L1正则惩罚项系数太小, 导致稀疏训练出来的模型参数没有产生稀疏化的效果

同样问题是yolov8n,然后还报错“bn has no activate elements”

**Comment by JasonSloan** [comment]
> > > 我想会不会是你稀疏化训练的轮数不够, 或者L1正则惩罚项系数太小, 导致稀疏训练出来的模型参数没有产生稀疏化的效果
> 
> 同样问题是yolov8n,然后还报错“bn has no activate elements”

代码哪一行报错?
