### ISSUE TITLE
有关稀疏训练过程的问题

### ISSUE THREAD

**Issue by zhDai** [JasonSloan/learning-notebook#2]
你好，我目前遇到个问题，通过稀疏训练好的模型结果比普通训练训练好的模型结果差，那后面还能稀疏训练好的模型进行prune及finetune吗？

**Comment by JasonSloan** [comment]
> 你好，我目前遇到个问题，通过稀疏训练好的模型结果比普通训练训练好的模型结果差，那后面还能稀疏训练好的模型进行prune及finetune吗？

要差多少呢

**Comment by zhDai** [comment]
差挺多的，4-5个点

**Comment by JasonSloan** [comment]
> 差挺多的，4-5个点

理论上不会变得差很多,  把正则化系数调的低一点试试还会变那么差吗

**Comment by zhDai** [comment]
好的，谢谢你的回复，我再尝试下
